### ISSUE TITLE
Write Integration Tests

### ISSUE THREAD

**Issue by shaqq** [theonion/videojs-vast-plugin#6]
It's hooked up to Sauce Labs - now lets write some actual tests

**Comment by pcting** [comment]
I'd just like to report that tests in general seem to be broken on mater right now.

```
$ npm test
...
>> ReferenceError: desireds is not defined
>>     at Object.module.exports (/home/pcting/code/videojs-vast-plugin/Gruntfile.js:70:52)
>>     at loadTask (/home/pcting/code/videojs-vast-plugin/node_modules/grunt/lib/grunt/task.js:325:10)
>>     at Task.task.init (/home/pcting/code/videojs-vast-plugin/node_modules/grunt/lib/grunt/task.js:437:5)
>>     at Object.grunt.tasks (/home/pcting/code/videojs-vast-plugin/node_modules/grunt/lib/grunt.js:120:8)
>>     at Object.module.exports [as cli] (/home/pcting/code/videojs-vast-plugin/node_modules/grunt/lib/grunt/cli.js:38:9)
>>     at Object.<anonymous> (/home/pcting/lib/node_modules/grunt-cli/bin/grunt:45:20)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
```

There used to be a line at the top of Gruntfile.js:
```
var desireds = require('./spec/desireds.js');
```
Both the line above and the spec/desireds.js no longer exist.

**Comment by pcting** [comment]
Ignore my last statment, I just noticed tests are being run on Travis with `grunt karma`.
