### ISSUE TITLE
It is dropping my vast tag .. 

### ISSUE THREAD

**Issue by syedbaqarrizvi** [theonion/videojs-vast-plugin#90]
The problem is i am using google DFP vast it is working fine in. other player and working in this plugin as well but after playing add 2 3 times it shows this error in my console .

`D ERROR: VAST Error: on VASTClient.getVASTAd.validateVASTTree, no Ad in VAST tree VASTErrorcode: 303message: "VAST Error: on VASTClient.getVASTAd.validateVASTTree, no Ad in VAST tree"stack: (...)__proto__: Error
    at Object.23 (http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:3739:23)
    at s (http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:1:254)
    at http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:1:305
    at Object.33.../../utils/dom (http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:5116:17)
    at s (http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:1:254)
    at http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:1:305
    at Object.30.../../utils/utilityFunctions (http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:4636:22)
    at s (http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:1:254)
    at http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:1:305
    at Object.18.../../utils/utilityFunctions (http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs_4.vast.vpaid.js:3219:16)name: "VAST Error"stack: (...)get stack: stack()set stack: stack()__proto__: Object Array[0]`

i dont know why is that tag is working fine everywhere .

My dfp tag is 

https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/39243592/387337752&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]

**Comment by vaquiceno** [comment]
did you find any solution?

**Comment by M-arcus** [comment]
Same issue here, but I get an earlier error, too

```
script.js Uncaught TypeError: Cannot read property 'removeChild' of null
    at initVideo (<anonymous>:78:24)
    at startAd (<anonymous>:24:5)
    at <anonymous>:1:1
```
Line 78: `videoContainer.removeChild(sdkVideoPlayer);`

VideoContainer: `videoContainer = document.getElementById("video-container");` which is null

Maybe this will help someone...
